# Generated by Django 4.2.4 on 2023-11-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursoeducativo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='recursos'),
        ),
    ]
