# Generated by Django 4.2.4 on 2023-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recursoeducativo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoeducativo',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
