# Generated by Django 4.2.4 on 2023-11-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_recursoeducativo_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoeducativo',
            name='imagen',
            field=models.URLField(),
        ),
    ]
