# Generated by Django 4.2.4 on 2023-12-14 03:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_recursoeducativo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_hora_fin',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_hora_inicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_fin_hora',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_inicio_hora',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
