# Generated by Django 4.2.4 on 2023-12-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cita_fecha_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='imagen',
            field=models.URLField(default='https://www.pngitem.com/pimgs/m/146-1468479_my-profile-icon-blank-profile-picture-circle-hd.png'),
        ),
    ]
