# Generated by Django 4.2.4 on 2023-12-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cita_estado_alter_cita_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_fin',
        ),
    ]
