# Generated by Django 4.2.4 on 2023-12-14 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_cita_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
